export const theme = {
  colors: {
    background: '#FAFAF7',
    surface: '#FFFFFF',
    text: '#0F1B2D',
    textSecondary: '#60718A',
    accent: '#C8A96A',
    success: '#2D8A7E',
    error: '#9B2C2C',
    border: '#E5E7EB',
    disabled: '#9CA3AF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
};